branch-defaults:
  main:
    environment: null
    group_suffix: null
global:
  application_name: codezorro02
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
