# Generated by Django 3.2.7 on 2021-09-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einstein', '0002_appuser_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='User',
        ),
    ]
