# Generated by Django 3.2.7 on 2021-09-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einstein', '0005_language_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
