# Generated by Django 3.2.7 on 2021-09-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einstein', '0007_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Narrative',
        ),
    ]
