# Generated by Django 3.2.7 on 2021-09-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einstein', '0008_rename_text_narrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
