# Generated by Django 3.2.8 on 2021-10-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einstein', '0011_email_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=95),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
